# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a8b767156fae916e077ca993512befd6cfe2efd4c44223f2bcdbb60a13d33d47a1dab2f8ffc85c87fa5fa0eb7e1affc9bbfc07fd5c83a7b65cb4bbe9516f3c
  dropbox:
    app_key: 11zhc1jonrxnt8s
    app_secret: lj2xhsqqr2ded34
    mode: dropbox
    access_token: hnwfqknfq2dhd2i1
    access_token_secret: v143xqottray6u6
    user_id: 559697490


test:
  secret_key_base: 627690ba9a92bd9224d2a21301aa257e117afc42e6442d8411301b780b9ee807e4484da7c6387b84cf029c002a5c0cddf0c3a13b24d010dc5f27c2c4791072ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  dropbox:
    app_key: 11zhc1jonrxnt8s
    app_secret: lj2xhsqqr2ded34
    mode: dropbox
    access_token: hnwfqknfq2dhd2i1
    access_token_secret: v143xqottray6u6
    user_id: 559697490